packages:
  # Applications
  - 'apps/*'
  
  # Shared packages
  - 'packages/*'
  
  # Tools
  - 'tools/*'
  
  # Exclude test and temporary directories
  - '!**/test/**'
  - '!**/dist/**'
  - '!**/build/**'
  - '!**/data/**'
